### ISSUE TITLE
Where are `-ee` and `-se` modules?

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/arquillian-container-weld#34]
I've noticed that the structure has been changed with `2.0.0` version. What happened with the other modules? If it's desired we should probably also remote `-root` in such a case.

Also the name of `-root` pom is a bit misleading and it results with a weird blog post title and module name on `arquillian.org` - `Arquillian Container Weld Root POM 2.0.0.Beta3 Released`.

**Comment by bartoszmajsak** [comment]
Would be great to clean it up @johnament @tremes.

**Comment by johnament** [comment]
@bartoszmajsak I added that to make room for #32/#33 .  I believe -ee and -se were removed and provide a consolidated module that can do both -se and -ee.

**Comment by johnament** [comment]
What would you recommend we name the root level POM? just "arquillian-container-weld" ?

**Comment by tremes** [comment]
There is no need for `ee` and `se` modules. In general it was only code duplication. You can change the environment either programmatically or by configuration property as described in the README file!

I agree the `root` pom naming is currently weird since there is only one "impl" module but I think John suggested to introduce new integration tests.

**Comment by bartoszmajsak** [comment]
> as described in the README file!

ok, ok :) Missed that part.

**Comment by bartoszmajsak** [comment]
Shall we deprecate this repository then? https://github.com/arquillian/arquillian-container-weld

**Comment by tremes** [comment]
Yes we can.
